# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a3d5b74abb0aece80e14ade653c388505b30b67fafb341f0eb78191dd35ab18a949ef315152fd24753f866112d857493fa37c33ee90cb2f718127ac032f70c4
  clickatel_username: Vizitco
  clickatel_password: D1t1sMyGeHe1m
  clickatel_api_id: 3617769

test:
  secret_key_base: 9e4de84ae420ed2fb640c797eec3c375f89fda0c4a83297d4fdc62dc23695ad16ffa82ee03b8b9345d154fc732abf7190200de8f35351c58c46669cd25f73885

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  clickatel_username: Vizitco
  clickatel_password: D1t1sMyGeHe1m
  clickatel_api_id: 3617769
 